### ISSUE TITLE
Can't install kivy with consistent gstreamer

### ISSUE THREAD

**Issue by scopatz** [conda-forge/kivy-feedstock#29]
Hi there, It seems like kivy is getting built with gstreamer v1.18.4 and gst-pulgins-base 1.14.4.  This inconsistency makes it impossible to install kivy and other plugins (like gst-plugins-ugly).  The build where you can see this happening is at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=305207&view=logs&j=bb1c2637-64c6-57bd-9ea6-93823b2df951&t=350df31b-3291-5209-0bb7-031395f0baa1&l=443 

This is odd because gstreamer and gst-plugins-base are both getting pinned to 1.18 in the conda-forge pinnings file here: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L386

I am not sure what is causing this but it is very odd.

**Comment by scopatz** [comment]
FWIW - I have built a version of kivy that actually works with gstreamer on my own channel here: https://anaconda.org/scopatz/kivy

**Comment by matham** [comment]
You may want to bring it up on the conda gitter channels. It's possible it's a degeneracy in the conda dependency graph solver algorithm!?

**Comment by scopatz** [comment]
CC @conda-forge/core

**Comment by wolfv** [comment]
There was a similar comment on the gitter chat recently: https://gitter.im/conda-forge/conda-forge.github.io?at=60802a0ba2ac0d38e7cd2f41

Although I am not aware of any major changes in this area.

**Comment by mbargull** [comment]
The migration only moved gstreamer forward but not gst-plugins-base which is why there was a mismatch.
For the last rebuild of this feedstock, you did not rerender in gh-28 and thus did not update the gst-plugins-base pin.

**Comment by wolfv** [comment]
do we need to move some packages to broken?

**Comment by matham** [comment]
https://github.com/conda-forge/kivy-feedstock/pull/31 should have fixed it!
