### ISSUE TITLE
Request to build kivy with gstreamer=1.20+

### ISSUE THREAD

**Issue by farleylai** [conda-forge/kivy-feedstock#39]
It seems like the latest `kivy` distribution on conda-forge assumes `gstreamer<1.19` when `gstreamer=1.20` was just released.
Packages such as `gst-rtsp-server` is going to check `gstreamer>=1.19` that cannot be updated due to the conflict with kivy as follows:

```
Encountered problems while solving:
  - package kivy-2.0.0-py39h99e5976_4 requires gstreamer >=1.18.5,<1.19.0a0, but none of the providers can be installed
```

Any chance to update soon?

**Comment by matham** [comment]
I'm not sure why we are stuck with a older version. We don't pin the gstreamer version, it's conda-forge itself that pinned the version. E.g. here: https://github.com/conda-forge/kivy-feedstock/pull/27. It seems to originate from here: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L445.

**Comment by farleylai** [comment]
Got it. Thanks.
